# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gear' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.6.4'
#  pod 'GoogleSignIn'
#  pod 'FBSDKCoreKit'
#  pod 'FBSDKLoginKit'
  pod 'SwiftLint'
  pod 'SnapKit', '~> 5.6.0'

  target 'GearTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GearUITests' do
    # Pods for testing
  end

end
